<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

<xacro:property name="body_link_x_dim" value="1"/>
<xacro:property name="body_link_y_dim" value="0.6"/>
<xacro:property name="body_link_z_dim" value="0.3"/>

<xacro:property name="wheel_link_radius" value="0.15"/>
<xacro:property name="wheel_link_length" value="0.1"/>
<xacro:property name="wheel_link_z_location" value="-0.1"/>


<xacro:property name="body_density" value="2710.0"/>
<xacro:property name="wheel_density" value="2710.0"/>

<xacro:property name="pi_const" value="3.14159265"/>

<xacro:property name="body_mass" value="${body_link_x_dim*body_link_y_dim*body_link_z_dim*body_density}"/>
<xacro:property name="wheel_mass" value="${pi_const*wheel_link_radius*wheel_link_radius*wheel_link_length*wheel_density}"/>


<xacro:property name="Iz_wheel" value="${0.5*wheel_mass*wheel_link_radius*wheel_link_radius}"/>
<xacro:property name="I_wheel" value="${(1.0/12.0)*wheel_mass*(3.0*wheel_link_radius*wheel_link_radius+wheel_link_length*wheel_link_length)}"/>


<xacro:macro name="inertia_wheel">
    <inertial>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <mass value="${wheel_mass}"/>
    <inertia ixx="${I_wheel}" ixy="0.0" ixz="0.0" iyy="${I_wheel}" iyz="0" izz="${Iz_wheel}"/>
    </inertial>
</xacro:macro>



<link name="dummy">
</link>
    <joint name="base_footprint_joint" type="fixed">
        <parent link="dummy"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="base_footprint">
    </link>

<joint name="dummy_joint" type="fixed">
    <parent link="dummy"/>
    <child link="body_link"/>
</joint>

<link name="body_link">
    <visual>
        <geometry>
            <box size="${body_link_x_dim} ${body_link_y_dim} ${body_link_z_dim}"/>
        </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
    </visual>
    <collision>
        <geometry>
            <box size="${body_link_x_dim} ${body_link_y_dim} ${body_link_z_dim}"/>        </geometry>
        <origin rpy="0 0 0" xyz="0 0 0"/>
    </collision>
    <inertial>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <mass value="${body_mass}"/>
        <inertia ixx="${(1.0/12.0)*body_mass*(body_link_y_dim*body_link_y_dim+body_link_z_dim*body_link_z_dim)}" 
            ixy="0" ixz="0" 
            iyy="${(1.0/12.0)*body_mass*(body_link_x_dim*body_link_x_dim+body_link_z_dim*body_link_z_dim)}" iyz="0" 
            izz="${(1.0/12.0)*body_mass*(body_link_y_dim*body_link_y_dim+body_link_x_dim*body_link_x_dim)}"/>
    </inertial>
</link>
<gazebo reference="body_link">
    <material>Gazebo/Red</material>
</gazebo>
<joint name="wheel1_joint" type="continuous">
    <parent link="body_link"/>
    <child link="wheel1_link"/>
    <origin xyz="${-body_link_x_dim/2+1.2*wheel_link_radius} ${-body_link_y_dim/2-wheel_link_length/2} ${wheel_link_z_location}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit effort="1000" velocity="1000"/>
    <dynamics damping="1.0" friction="1.0"/>

</joint>

<link name="wheel1_link">
    <visual>
        <geometry>
            <cylinder radius="${wheel_link_radius}" length="${wheel_link_length}" />
        </geometry>
            <origin xyz="0 0 0" rpy="1.57079632 0 0"/>
    </visual>
    <collision>
        <geometry>
            <sphere radius="${wheel_link_radius}"/>
            </geometry>
        <origin xyz="0 0 0" rpy="1.57079632 0 0"/>
    </collision>
    <xacro:inertia_wheel/>
</link>
<gazebo reference="wheel1_link">
    <material>Gazebo/Black</material>
</gazebo>
<joint name="wheel2_joint" type="continuous">
    <parent link="body_link"/>
    <child link="wheel2_link"/>
    <origin xyz="${-body_link_x_dim/2+1.2*wheel_link_radius} ${body_link_y_dim/2+wheel_link_length/2} ${wheel_link_z_location}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit effort="1000" velocity="1000"/>
    <dynamics damping="1.0" friction="1.0"/>

</joint>

<link name="wheel2_link">
    <visual>
        <geometry>
            <cylinder radius="${wheel_link_radius}" length="${wheel_link_length}" />
        </geometry>
            <origin xyz="0 0 0" rpy="1.57079632 0 0"/>
    </visual>
    <collision>
        <geometry>
            <sphere radius="${wheel_link_radius}"/>
                  <origin xyz="0 0 0" rpy="1.57079632 0 0"/>
        </geometry>
    </collision>
    <xacro:inertia_wheel/>
</link>
<gazebo reference="wheel2_link">
    <material>Gazebo/Black</material>
</gazebo>


<joint name="wheel3_joint" type="continuous">
    <parent link="body_link"/>
    <child link="wheel3_link"/>
    <origin xyz="${body_link_x_dim/2-1.2*wheel_link_radius} ${-body_link_y_dim/2-wheel_link_length/2} ${wheel_link_z_location}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit effort="1000" velocity="1000"/>
    <dynamics damping="1.0" friction="1.0"/>

</joint>

<link name="wheel3_link">
    <visual>
        <geometry>
            <cylinder radius="${wheel_link_radius}" length="${wheel_link_length}" />
        </geometry>
            <origin xyz="0 0 0" rpy="1.57079632 0 0"/>
    </visual>
    <collision>
        <geometry>
            <sphere radius="${wheel_link_radius}"/>
            <origin xyz="0 0 0" rpy="1.57079632 0 0"/></geometry>
    </collision>
    <xacro:inertia_wheel/>
</link>
<gazebo reference="wheel3_link">
    <material>Gazebo/Black</material>
</gazebo>

<joint name="wheel4_joint" type="continuous">
    <parent link="body_link"/>
    <child link="wheel4_link"/>
    <origin xyz="${body_link_x_dim/2-1.2*wheel_link_radius} ${body_link_y_dim/2+wheel_link_length/2} ${wheel_link_z_location}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit effort="1000" velocity="1000"/>
<dynamics damping="1.0" friction="1.0"/>

</joint>

<link name="wheel4_link">
    <visual>
        <geometry>
            <cylinder radius="${wheel_link_radius}" length="${wheel_link_length}" />
        </geometry>
            <origin xyz="0 0 0" rpy="1.57079632 0 0"/>
    </visual>
    <collision>
        <geometry>
            <sphere radius="${wheel_link_radius}"/>
        <origin xyz="0 0 0" rpy="1.57079632 0 0"/>
        </geometry>
    </collision>
    <xacro:inertia_wheel/>
</link>
<gazebo reference="wheel4_link">
    <material>Gazebo/Black</material>
</gazebo>

</robot>
