controller_manager:
  ros__parameters:
    update_rate: 30
    # use_sim_time: true

    diff_cont:
      type: diff_drive_controller/DiffDriveController
      # control_period: 0.033333333

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_cont:
  ros__parameters:
    publish_rate: 30.0

    base_frame_id: body_link
    wheels_per_side: 2
    left_wheel_names: ['wheel4_joint','wheel2_joint']
    right_wheel_names: ['wheel3_joint','wheel1_joint']
    wheel_separation: 0.6
    wheel_radius: 0.15

    use_stamped_vel: false
    
    # open_loop: false    

    
    # wheel_separation_multiplier: x
    # left_wheel_radius_multiplier: x
    # right_wheel_radius_multiplier: x

    # odom_frame_id: x
    # pose_covariance_diagonal: x
    # twist_covariance_diagonal: x
    # open_loop: x
    # enable_odom_tf: x

    # cmd_vel_timeout: x
    # publish_limited_velocity: x
    # velocity_rolling_window_size: x
    

    # linear.x.has_velocity_limits: false
    # linear.x.has_acceleration_limits: false
    # linear.x.has_jerk_limits: false
    # linear.x.max_velocity: NAN
    # linear.x.min_velocity: NAN
    # linear.x.max_acceleration: NAN
    # linear.x.min_acceleration: NAN
    # linear.x.max_jerk: NAN
    # linear.x.min_jerk: NAN

    # angular.z.has_velocity_limits: false
    # angular.z.has_acceleration_limits: false
    # angular.z.has_jerk_limits: false
    # angular.z.max_velocity: NAN
    # angular.z.min_velocity: NAN
    # angular.z.max_acceleration: NAN
    # angular.z.min_acceleration: NAN
    # angular.z.max_jerk: NAN
    # angular.z.min_jerk: NAN
    # pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.03]
    # twist_covariance_diagonal: [0.001, 0.001, 0.001, 1000000.0, 1000000.0, 0.03]
    # cmd_vel_timeout: 0.25

    # Publish final output cmd_vel to /jackal_velocity_controller/cmd_vel_out
    # publish_cmd: true

    # k_l: 0.1
    # k_r: 0.1

    # Odometry fused with IMU is published by robot_localization, so
    # no need to publish a TF based on encoders alone.
    # enable_odom_tf: true

    # Wheel separation and radius multipliers
    # wheel_separation_multiplier: 1.5 # default: 1.0
    # wheel_radius_multiplier    : 1.0 # default: 1.0

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    # linear:
    #   x:
    #     has_velocity_limits    : true
    #     max_velocity           : 50.0   # m/s
    #     has_acceleration_limits: true
    #     max_acceleration       : 20.0   # m/s^2
    # angular:
    #   z:
    #     has_velocity_limits    : true
    #     max_velocity           : 50.0   # rad/s
    #     has_acceleration_limits: true
    #     max_acceleration       : 25.0   # rad/s^2



joint_broad:
  ros__parameters:
    publish_rate: 30.0
